const fs = require('fs');
const path = require('path');

const eventsPath = path.join(__dirname, 'events.json');
const events = JSON.parse(fs.readFileSync(eventsPath, 'utf-8'));

const newEvents = [
  {
    "id": "34",
    "title": "THE MARAVILLOSOS TENORS",
    "date": "2025-12-05",
    "time": "20:00",
    "location": "Plaza del Mercado",
    "description": "A Christmas Concert. Concierto navideño en vivo.",
    "descriptionExtended": "A Christmas Concert. Concierto navideño en vivo. Los Maravillosos Tenors presentan un espectáculo navideño con canciones clásicas.",
    "price": "Gratuito.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 12.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "35",
    "title": "FIESTA INFANTIL DE COMERCIO",
    "date": "2025-12-06",
    "time": "10:00",
    "location": "Avenida Andalucía",
    "description": "Juegos, talleres, buñuelos, personajes Disney y colchones.",
    "descriptionExtended": "Fiesta especial para los niños con juegos interactivos, talleres creativos, buñuelos tradicionales, personajes Disney y colchones hinchables.",
    "price": "Gratuito.",
    "category": "Familiar e Infantil",
    "image": "./Eventos/evento 6.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "36",
    "title": "MERIENDA TRADICIONAL NAVIDEÑA",
    "date": "2025-12-12",
    "time": "17:30",
    "location": "Plaza El Salvador",
    "description": "Merienda navideña tradicional a cargo de varias cofradías.",
    "descriptionExtended": "Merienda navideña tradicional preparada por varias cofradías locales. Disfruta de productos típicos de la zona en ambiente festivo.",
    "price": "Gratuito (Consumiciones en barra).",
    "category": "Tradición Local",
    "image": "./Eventos/evento 9.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "37",
    "title": "IX CERTAMEN DE POSTALES NAVIDEÑAS",
    "date": "2025-12-17",
    "time": "10:00 a 13:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Certamen de postales navideñas.",
    "descriptionExtended": "IX edición del Certamen de Postales Navideñas. Exhibición de trabajos creativos navideños.",
    "price": "Gratuito.",
    "category": "Familiar e Infantil",
    "image": "./Eventos/evento 10.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "38",
    "title": "CERTAMEN DE VILLANCICOS",
    "date": "2025-12-17",
    "time": "10:00 a 13:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Certamen de villancicos. Competición de grupos de canto.",
    "descriptionExtended": "Certamen de villancicos donde grupos locales compiten presentando sus mejores interpretaciones de canciones navideñas tradicionales.",
    "price": "Gratuito.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "39",
    "title": "RECORRIDO DE VILLANCICOS",
    "date": "2025-12-18",
    "time": "19:30",
    "location": "Pl. Higuitos → Pl. Ayuntamiento → Pl. Madrid → Pl. de la Rosa",
    "description": "Recorrido de villancicos por las plazas principales. Agrupación Pulso y Púa.",
    "descriptionExtended": "La agrupación musical Pulso y Púa recorre las principales plazas de Almuñécar interpretando villancicos tradicionales navideños.",
    "price": "Gratuito.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "40",
    "title": "VISITA DE PAPÁ NOEL",
    "date": "2025-12-19",
    "time": "17:00",
    "location": "Plaza del Mercado",
    "description": "Visita de Papá Noel. Colchones y merienda tradicional.",
    "descriptionExtended": "Papá Noel se instalará en la Plaza del Mercado para saludar a los niños. Incluye colchones hinchables y merienda tradicional a cargo de la Cofradía del Despojado.",
    "price": "Gratuito.",
    "category": "Familiar e Infantil",
    "image": "./Eventos/evento 9.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "41",
    "title": "VIDEO MAPPING PLAZA DEL MERCADO",
    "date": "2025-12-19",
    "time": "19:30 a 22:00",
    "location": "Plaza del Mercado",
    "description": "Espectáculo de proyecciones navideñas.",
    "descriptionExtended": "Espectáculo visual con video mapping navideño en la fachada de la plaza. Proyecciones sincronizadas con música festiva.",
    "price": "Gratuito.",
    "category": "Tradición Local",
    "image": "./Eventos/evento 1.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "42",
    "title": "GRAN ZAMBOMBÁ GRUPO ORTIGOSA",
    "date": "2025-12-19",
    "time": "20:00",
    "location": "Plaza del Mercado",
    "description": "Gran zambombá con Grupo Ortigosa.",
    "descriptionExtended": "Gran zambombá con el famoso Grupo Ortigosa presentando música y danzas tradicionales navideñas.",
    "price": "Gratuito.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 10.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "43",
    "title": "BLUE MOONS ESPECIAL NAVIDAD",
    "date": "2025-12-20",
    "time": "20:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Blue Moons presenta concierto especial de Navidad.",
    "descriptionExtended": "Blue Moons ofrece un concierto especial de Navidad con sus mejores temas y versiones navideñas.",
    "price": "Entradas taquilla y Viajes Azulmarino.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 12.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "44",
    "title": "ALMUÑÉCAR RECIBE LA LUZ DE BELÉN",
    "date": "2025-12-20",
    "time": "Desde 18:00",
    "location": "Templo El Salvador (18:00) → Parroquia Encarnación (19:00)",
    "description": "Procesión de la Luz de Belén por las iglesias principales.",
    "descriptionExtended": "Almuñécar recibe la Luz de Belén en una procesión especial que conecta los templos principales de la ciudad. Inicio en Templo El Salvador a las 18:00 y Parroquia Encarnación a las 19:00.",
    "price": "Gratuito.",
    "category": "Actos Religiosos",
    "image": "./Eventos/evento 6.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "45",
    "title": "NAVIDAD SE VIVE AL AIRE LIBRE",
    "date": "2025-12-20",
    "time": "12:00",
    "location": "Parque El Pozuelo",
    "description": "Papá Noel, colchones, música, actividades deportivas y paella popular.",
    "descriptionExtended": "Día completo de diversión navideña en el Parque El Pozuelo con la visita de Papá Noel, colchones hinchables, música en vivo, actividades deportivas y comida popular con paella.",
    "price": "Gratuito (paella con consumición).",
    "category": "Familiar e Infantil",
    "image": "./Eventos/evento 7.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "46",
    "title": "PASACALLES 22 DICIEMBRE",
    "date": "2025-12-22",
    "time": "18:00",
    "location": "Calles del Centro Comercial",
    "description": "Pasacalles navideño.",
    "descriptionExtended": "Pasacalles navideño por las calles del centro comercial con la Charanga Imperio Sexitano y Banda Municipal.",
    "price": "Gratuito.",
    "category": "Familiar e Infantil",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "47",
    "title": "PASACALLES 29 DICIEMBRE",
    "date": "2025-12-29",
    "time": "18:00",
    "location": "Calles del Centro Comercial",
    "description": "Pasacalles navideño.",
    "descriptionExtended": "Pasacalles navideño por las calles del centro comercial con la Charanga Imperio Sexitano y Banda Municipal.",
    "price": "Gratuito.",
    "category": "Familiar e Infantil",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "48",
    "title": "PASACALLES 3 ENERO",
    "date": "2026-01-03",
    "time": "18:00",
    "location": "Calles del Centro Comercial",
    "description": "Pasacalles navideño de Reyes.",
    "descriptionExtended": "Pasacalles navideño de Reyes por las calles del centro comercial con la Charanga Imperio Sexitano y Banda Municipal.",
    "price": "Gratuito.",
    "category": "Familiar e Infantil",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "49",
    "title": "ENCUENTRO DE BANDAS",
    "date": "2025-12-28",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Encuentro de bandas musicales locales.",
    "descriptionExtended": "Encuentro de bandas musicales donde se reúnen bandas locales para un concierto conjunto.",
    "price": "Entrada libre hasta completar aforo.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "50",
    "title": "CONCIERTO JOVEN BANDA PROVINCIAL",
    "date": "2025-12-28",
    "time": "19:00",
    "location": "Plaza del Ayuntamiento",
    "description": "Concierto al aire libre de la Joven Banda Provincial.",
    "descriptionExtended": "Concierto al aire libre en la Plaza del Ayuntamiento presentando la Joven Banda Provincial con un repertorio variado.",
    "price": "Gratuito.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "51",
    "title": "CONCIERTO DE REYES SOLIDARIO AFAVIDA",
    "date": "2026-01-03",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Concierto de Reyes solidario a favor de AFAVIDA.",
    "descriptionExtended": "Concierto solidario de Reyes para recaudar fondos a favor de la asociación AFAVIDA.",
    "price": "Entradas taquilla, Azulmarino y www.bravoentradas.es.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 13.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "52",
    "title": "LOS BUENOS DEMONIOS",
    "date": "2025-12-01",
    "time": "19:30",
    "location": "Sala Conferencias Casa de la Cultura",
    "description": "Evento cultural.",
    "descriptionExtended": "Actividad cultural: Los buenos demonios.",
    "price": "Entrada libre.",
    "category": "Teatro y Danza",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "53",
    "title": "EXPOSICIÓN MARINAS Y FLORES",
    "date": "2025-12-01",
    "time": "10:00 a 13:00 y 17:00 a 19:00",
    "location": "Sala Exposiciones Casa de la Cultura",
    "description": "Exposición de obras de Aintzana Zarroa.",
    "descriptionExtended": "Exposición de obras pictóricas titulada \"Marinas y flores\" del artista Aintzana Zarroa.",
    "price": "Entrada libre.",
    "category": "Exposiciones",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "54",
    "title": "PROYECCIÓN CORTOS FESTIVAL JÓVENES REALIZADORES",
    "date": "2025-12-02",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Proyección de cortos del Palmarés del Festival de Jóvenes Realizadores.",
    "descriptionExtended": "Sesión de proyección de los cortometrajes ganadores del Palmarés del Festival de Jóvenes Realizadores.",
    "price": "Entrada libre.",
    "category": "Cine",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "55",
    "title": "TERTULIA LITERARIA FEDERICO GARCÍA LORCA",
    "date": "2025-12-04",
    "time": "19:00",
    "location": "Biblioteca Municipal",
    "description": "Tertulia literaria dedicada a Federico García Lorca.",
    "descriptionExtended": "Tertulia literaria participativa dedicada a la vida y obra de Federico García Lorca.",
    "price": "Gratuito. Inscripción: biblioteca@almunecar.es",
    "category": "Literatura",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "56",
    "title": "CONCIERTO TRÍO DE CAÑAS ÄGLAE",
    "date": "2025-12-04",
    "time": "19:30",
    "location": "Auditorio Casa de la Cultura",
    "description": "Concierto del Trío de Cañas Äglae.",
    "descriptionExtended": "Concierto musical del Trío de Cañas Äglae.",
    "price": "Entradas taquilla, Azulmarino, Librería Contreras.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "57",
    "title": "HORA DE LA RISA",
    "date": "2025-12-05",
    "time": "20:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Espectáculo de humor. Juancho Bernabé y Jesús Tapia.",
    "descriptionExtended": "Espectáculo de humor presentado por Juancho Bernabé y Jesús Tapia.",
    "price": "Entradas taquilla y lacocheraentradas.com",
    "category": "Teatro y Danza",
    "image": "./Eventos/evento 8.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "58",
    "title": "GREEN WOLF - ORGAN TRIO",
    "date": "2025-12-06",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Green Wolf | Organ Trio. Blues y Rock.",
    "descriptionExtended": "Concierto de Green Wolf | Organ Trio presentando blues, rock y géneros musicales variados.",
    "price": "Entradas taquilla, Azulmarino, Contreras, lacochera.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "59",
    "title": "UNIVERSO FLAMENCO - IRENE LA SERRANILLA",
    "date": "2025-12-07",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Universo Flamenco con Irene \"La Serranilla\".",
    "descriptionExtended": "Espectáculo flamenco presentado por Irene \"La Serranilla\".",
    "price": "Entradas taquilla, Azulmarino, bravoentradas.es",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 10.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "60",
    "title": "FIESTAS INMACULADA CONCEPCIÓN",
    "date": "2025-12-08",
    "time": "11:00 y 12:00",
    "location": "Polideportivo de la Carrera",
    "description": "Misa y desayuno conmemorativo.",
    "descriptionExtended": "Celebración de la Inmaculada Concepción con misa a las 11:00 y desayuno a las 12:00.",
    "price": "Gratuito.",
    "category": "Actos Religiosos",
    "image": "./Eventos/evento 6.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "61",
    "title": "TANGO Y FLAMENCO - RAÍCES ENCONTRADAS",
    "date": "2025-12-08",
    "time": "19:30",
    "location": "Auditorio Casa de la Cultura",
    "description": "Tango y Flamenco \"Raíces encontradas\" con Fabian Carbone y La Almendrita.",
    "descriptionExtended": "Espectáculo fusionando tango y flamenco presentado por Fabian Carbone y La Almendrita.",
    "price": "www.conciertosengranada.es",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 10.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "62",
    "title": "CUENTACUENTOS PARA ADULTOS",
    "date": "2025-12-09",
    "time": "19:00",
    "location": "Biblioteca Municipal",
    "description": "Cuentacuentos especial para adultos con José Alonso.",
    "descriptionExtended": "Sesión de cuentacuentos dirigida a adultos presentada por José Alonso.",
    "price": "Gratuito.",
    "category": "Literatura",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "63",
    "title": "MARTES DE CINE - TRES AMIGAS V.O.S.E",
    "date": "2025-12-09",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Sesión de Martes de Cine: \"Tres amigas\" versión original subtitulada.",
    "descriptionExtended": "Proyección de la película \"Tres amigas\" en versión original subtitulada en español.",
    "price": "Gratuito.",
    "category": "Cine",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "64",
    "title": "JOLÍS - BREL",
    "date": "2025-12-10",
    "time": "-",
    "location": "Auditorio Casa de la Cultura",
    "description": "Concierto tributo a Jacques Brel.",
    "descriptionExtended": "Espectáculo musical Jolís interpretando canciones de Jacques Brel.",
    "price": "Entradas taquilla, Azulmarino, bravoentradas.es",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 12.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "65",
    "title": "CONFERENCIA LA ZARZUELA",
    "date": "2025-12-11",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Conferencia sobre la Zarzuela por Juventudes Musicales.",
    "descriptionExtended": "Conferencia educativa sobre la zarzuela española presentada por Juventudes Musicales.",
    "price": "Entrada libre.",
    "category": "Teatro y Danza",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "66",
    "title": "Y AZNAVOUR, MOUSTAKI, PIAF...",
    "date": "2025-12-12",
    "time": "20:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Homenaje a Aznavour, Moustaki y Piaf.",
    "descriptionExtended": "Concierto homenaje a Charles Aznavour, Georges Moustaki y Edith Piaf.",
    "price": "Entradas taquilla, Azulmarino, bravoentradas.es",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 12.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "67",
    "title": "RICHARD RAY FARRELL - THE BEST OF BLUES",
    "date": "2025-12-13",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Richard Ray Farrell presenta \"The Best of Blues\".",
    "descriptionExtended": "Concierto de blues presentado por Richard Ray Farrell.",
    "price": "Entradas taquilla, Azulmarino, Contreras, lacochera.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 5.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "68",
    "title": "UN PASEO POR LA HISTORIA - ACUEDUCTO ROMANO",
    "date": "2025-12-13",
    "time": "10:30",
    "location": "Acueducto Romano",
    "description": "Visita guiada por la historia. Acueducto Romano.",
    "descriptionExtended": "Excursión arqueológica para conocer la historia del Acueducto Romano.",
    "price": "Gratuito. Inscripción: arqueologia@almunecar.es",
    "category": "Arqueología",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "69",
    "title": "MARTES DE CINE - MUY LEJOS",
    "date": "2025-12-16",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Sesión de Martes de Cine: \"Muy lejos\".",
    "descriptionExtended": "Proyección de la película \"Muy lejos\".",
    "price": "Gratuito.",
    "category": "Cine",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "70",
    "title": "PRESENTACIÓN NOVELA EL ADMINISTRADOR FIEL",
    "date": "2025-12-18",
    "time": "19:00",
    "location": "Biblioteca Municipal",
    "description": "Presentación de la novela \"El administrador fiel\" de Guillermo García Prieto.",
    "descriptionExtended": "Acto de presentación de la novela \"El administrador fiel\" del autor Guillermo García Prieto.",
    "price": "Entrada libre.",
    "category": "Literatura",
    "image": "./Eventos/evento 3.png",
    "isFeatured": false,
    "carouselImages": []
  },
  {
    "id": "71",
    "title": "LOVE FLAMENCO - ESPECTÁCULO FLAMENCO",
    "date": "2025-12-19",
    "time": "19:00",
    "location": "Auditorio Casa de la Cultura",
    "description": "Espectáculo flamenco Love Flamenco.",
    "descriptionExtended": "Espectáculo flamenco de primera calidad presentado por Love Flamenco.",
    "price": "www.loveflamenco.es y puntos de venta habituales.",
    "category": "Música y Conciertos",
    "image": "./Eventos/evento 10.png",
    "isFeatured": false,
    "carouselImages": []
  }
];

const combined = [...events, ...newEvents];

fs.writeFileSync(eventsPath, JSON.stringify(combined, null, 2), 'utf-8');
console.log(`✅ Se agregaron ${newEvents.length} eventos nuevos.`);
console.log(`📊 Total de eventos: ${combined.length}`);
