$file = 'events.json'
$content = Get-Content -Path $file -Raw

$content = $content -replace 'https://picsum\.photos/seed/2/800/600', './Eventos/evento 1.png'
$content = $content -replace 'https://picsum\.photos/seed/3/800/600', './Eventos/evento 1.png'
$content = $content -replace 'https://picsum\.photos/seed/4/800/600', './Eventos/evento 3.png'
$content = $content -replace 'https://picsum\.photos/seed/5/800/600', './Eventos/evento 1.png'
$content = $content -replace 'https://picsum\.photos/seed/6/800/600', './Eventos/evento 5.png'
$content = $content -replace 'https://picsum\.photos/seed/7/800/600', './Eventos/evento 6.png'
$content = $content -replace 'https://picsum\.photos/seed/8/800/600', './Eventos/evento 7.png'
$content = $content -replace 'https://picsum\.photos/seed/9/800/600', './Eventos/evento 8.png'
$content = $content -replace 'https://picsum\.photos/seed/10/800/600', './Eventos/evento 9.png'
$content = $content -replace 'https://picsum\.photos/seed/11/800/600', './Eventos/evento 10.png'
$content = $content -replace 'https://picsum\.photos/seed/12/800/600', './Eventos/evento 11.png'
$content = $content -replace 'https://picsum\.photos/seed/13/800/600', './Eventos/evento 12.png'
$content = $content -replace 'https://picsum\.photos/seed/14/800/600', './Eventos/evento 13.png'
$content = $content -replace 'https://picsum\.photos/seed/15/800/600', './Eventos/evento 10.png'
$content = $content -replace 'https://picsum\.photos/seed/16/800/600', './Eventos/evento 13.png'
$content = $content -replace 'https://picsum\.photos/seed/17/800/600', './Eventos/evento 10.png'
$content = $content -replace 'https://picsum\.photos/seed/18/800/600', './Eventos/evento 12.png'
$content = $content -replace 'https://picsum\.photos/seed/19/800/600', './Eventos/evento 9.png'
$content = $content -replace 'https://picsum\.photos/seed/20/800/600', './Eventos/evento 8.png'
$content = $content -replace 'https://picsum\.photos/seed/21/800/600', './Eventos/evento 11.png'
$content = $content -replace 'https://picsum\.photos/seed/22/800/600', './Eventos/evento 6.png'
$content = $content -replace 'https://picsum\.photos/seed/23/800/600', './Eventos/evento 9.png'
$content = $content -replace 'https://picsum\.photos/seed/24/800/600', './Eventos/evento 7.png'
$content = $content -replace 'https://picsum\.photos/seed/25/800/600', './Eventos/evento 8.png'
$content = $content -replace 'https://picsum\.photos/seed/26/800/600', './Eventos/evento 10.png'
$content = $content -replace 'https://picsum\.photos/seed/27/800/600', './Eventos/evento 12.png'
$content = $content -replace 'https://picsum\.photos/seed/28/800/600', './Eventos/evento 5.png'
$content = $content -replace 'https://picsum\.photos/seed/29/800/600', './Eventos/evento 13.png'
$content = $content -replace 'https://picsum\.photos/seed/30/800/600', './Eventos/evento 11.png'
$content = $content -replace 'https://picsum\.photos/seed/31/800/600', './Eventos/evento 6.png'
$content = $content -replace 'https://picsum\.photos/seed/32/800/600', './Eventos/evento 9.png'
$content = $content -replace 'https://picsum\.photos/seed/33/800/600', './Eventos/evento 7.png'
$content = $content -replace 'https://picsum\.photos/seed/34/800/600', './Eventos/evento 10.png'

Set-Content -Path $file -Value $content -Encoding UTF8
Write-Host 'Imágenes actualizadas exitosamente en events.json'
